// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBHr3_vUhpQ2_eK0c8z64jiFuOGCZ-Xw',
    appId: '1:831416949571:android:236550ddd1715cc62c2df6',
    messagingSenderId: '831416949571',
    projectId: 'tasty-cook-378113',
    storageBucket: 'tasty-cook-378113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCL6-2y5p_vS-q4UpH_w62Fj8DWHQQlF0',
    appId: '1:831416949571:ios:260bfa09d5f5a6b42c2df6',
    messagingSenderId: '831416949571',
    projectId: 'tasty-cook-378113',
    storageBucket: 'tasty-cook-378113.appspot.com',
    androidClientId: '831416949571-vl5igs5ltim3lvadnqu3konl5qm7j6q2.apps.googleusercontent.com',
    iosClientId: '831416949571-ls43d0irage6vsb91kl7s49p2b6u4pfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyCook',
  );
}
